/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class State {
  constructor(options: StateOptions)
  /**
   * Get the scale for a measurement.
   *
   * # Arguments
   *
   * * `measurement_id` - The id of the measurement.
   *
   * # Returns
   *
   * * `None` - If the measurement was not found.
   * * `Some(scale)` - If the scale was found.
   */
  getMeasurementScale(measurementId: string): Scale | null
  /**
   * Inserts or updates a page in the state.
   *
   * # Arguments
   *
   * * `page` - The page to insert or update.
   *
   * # Returns
   *
   * * `None` - If the page was not found.
   * * `Some(page)` - If the page was found and updated.
   */
  upsertPage(page: Page): Page | null
  /**
   * Inserts or updates a group in the state.
   *
   * # Arguments
   *
   * * `group` - The group to insert or update.
   *
   * # Returns
   *
   * * `None` - If the group was not found.
   * * `Some(group)` - If the group was found and updated.
   */
  upsertGroup(group: Group): Group | null
  /**
   * Inserts or updates a measurement in the state.
   *
   * # Arguments
   *
   * * `measurement` - The measurement to insert or update.
   *
   * # Returns
   *
   * * `None` - If the measurement was not found.
   * * `Some(measurement)` - If the measurement was found and updated.
   */
  upsertMeasurement(measurement: Measurement): Measurement | null
  /**
   * Inserts or updates a scale in the state.
   *
   * # Arguments
   *
   * * `scale` - The scale to insert or update.
   *
   * # Returns
   *
   * * `None` - If the scale was not found.
   * * `Some(scale)` - If the scale was found and updated.
   */
  upsertScale(scale: Scale): Scale | null
}

export interface Group {
  id: string
  name?: string
  measurementType: MeasurementType
}

export type Measurement =
  | { type: 'Count', id: string, pageId: string, groupId: string, points: [Point] }
  | { type: 'Polygon', id: string, pageId: string, groupId: string, points: Array<Point> }
  | { type: 'Polyline', id: string, pageId: string, groupId: string, points: Array<Point> }
  | { type: 'Rectangle', id: string, pageId: string, groupId: string, points: [Point, Point] }

export type MeasurementType =  'Area'|
'Linear'|
'Count';

export interface Page {
  id: string
  name?: string
  width?: number
  height?: number
  viewport?: PageViewport
}

export interface PageViewport {
  width: number
  height: number
}

export declare function plus100(input: number): number

/** Represents a 2D point with floating point coordinates */
export interface Point {
  x: number
  y: number
}

export type Scale =
  | { type: 'Area', id: string, pageId: string, scale: ScaleDefinition, boundingBox: [Point, Point] }
  | { type: 'Default', id: string, pageId: string, scale: ScaleDefinition }

export interface ScaleDefinition {
  pixelDistance: number
  realDistance: number
  unit: Unit
}

export interface StateOptions {
  pages: Array<Page>
  groups: Array<Group>
  measurements: Array<Measurement>
  scales: Array<Scale>
}

/** Measurement units supported by the system */
export type Unit = /** Imperial units */
'Yards'|
'Feet'|
'Inches'|
/** Metric units */
'Meters'|
'Centimeters';
