/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ContourWrapper {
	constructor(contour: ContourInput);
	/** Get the surface points for the contour. */
	getSurfacePoints(): Array<Point3D> | null;
	/**
	 * Compute cut/fill volume against a reference surface.
	 * Returns None if the surface mesh is not available (e.g. contour conversion failed).
	 */
	volumeAgainst(
		reference: ReferenceSurfaceInput,
		cellSize?: number | undefined | null,
	): VolumetricResult | null;
	/**
	 * Get the z value at a given x, y coordinate.
	 * Returns None if the surface mesh is not available (e.g. contour conversion failed).
	 */
	getZAt(x: number, y: number): number | null;
	/**
	 * Get scatter data for the contour.
	 * Returns None if the surface mesh is not available (e.g. contour conversion failed).
	 *
	 * # Arguments
	 *
	 * * `step` - The step size for the scatter data.
	 *
	 * # Returns
	 *
	 * * `Vec<Point3D>` - The scatter data.
	 * * `None` - If the surface mesh is not available (e.g. contour conversion failed).
	 */
	getScatterData(step: number): Array<Point3D> | null;
}

export declare class GroupWrapper {
	/** Get the id of the group. */
	get id(): string;
	get area(): UnitValue | null;
	get length(): UnitValue | null;
	get points(): number | null;
	get count(): number | null;
	get group(): Group;
}

export declare class MeasurementWrapper {
	get points(): number;
	get measurement(): Measurement;
	get area(): UnitValue | null;
	convertArea(unit: Unit): number | null;
	convertLength(unit: Unit): number | null;
	get length(): UnitValue | null;
	get scale(): Scale | null;
	get id(): string;
	get pageId(): string;
	get groupId(): string;
	get rawArea(): number;
	get rawPerimeter(): number;
}

export declare class TakeoffStateHandler {
	/**
	 * Creates a new state.
	 *
	 * # Arguments
	 *
	 * * `options` - The options for the state.
	 *
	 * # Returns
	 *
	 * * `State` - The new state.
	 */
	constructor(options?: StateOptions | undefined | null);
	getMeasurementsByGroupId(groupId: string): Array<MeasurementWrapper>;
	/**
	 * Get the scale for a measurement.
	 *
	 * # Arguments
	 *
	 * * `measurement_id` - The id of the measurement.
	 *
	 * # Returns
	 *
	 * * `None` - If the measurement was not found.
	 * * `Some(scale)` - If the scale was found.
	 */
	getMeasurementScale(measurementId: string): Scale | null;
	/**
	 * Inserts or updates a page in the state.
	 *
	 * # Arguments
	 *
	 * * `page` - The page to insert or update.
	 *
	 * # Returns
	 *
	 * * `None` - If the page was not found.
	 * * `Some(page)` - If the page was found and updated.
	 */
	upsertPage(page: Page): Page | null;
	removePage(pageId: string): Page | null;
	getGroup(groupId: string): GroupWrapper | null;
	/**
	 * Inserts or updates a group in the state.
	 *
	 * # Arguments
	 *
	 * * `group` - The group to insert or update.
	 *
	 * # Returns
	 *
	 * * `None` - If the group was not found.
	 * * `Some(group)` - If the group was found and updated.
	 */
	upsertGroup(group: Group): Group | null;
	/**
	 * Removes a group from the state.
	 *
	 * # Arguments
	 *
	 * * `group_id` - The id of the group to remove.
	 *
	 * # Returns
	 * * `None` - If the group was not found.
	 * * `Some(group)` - If the group was found and removed.
	 */
	removeGroup(groupId: string): Group | null;
	/**
	 * Inserts or updates a measurement in the state.
	 *
	 * # Arguments
	 *
	 * * `measurement` - The measurement to insert or update.
	 *
	 * # Returns
	 *
	 * * `None` - If the measurement was not found.
	 * * `Some(measurement)` - If the measurement was found and updated.
	 */
	upsertMeasurement(measurement: Measurement): Measurement | null;
	/**
	 * Removes a measurement from the state.
	 *
	 * # Arguments
	 *
	 * * `measurement_id` - The id of the measurement to remove.
	 *
	 * # Returns
	 *
	 * * `None` - If the measurement was not found.
	 * * `Some(measurement)` - If the measurement was found and removed.
	 */
	removeMeasurement(measurementId: string): Measurement | null;
	getMeasurement(measurementId: string): MeasurementWrapper | null;
	/**
	 * Inserts or updates a scale in the state.
	 *
	 * # Arguments
	 *
	 * * `scale` - The scale to insert or update.
	 *
	 * # Returns
	 *
	 * * `None` - If the scale was not found.
	 * * `Some(scale)` - If the scale was found and updated.
	 */
	upsertScale(scale: Scale): Scale | null;
	/**
	 * Removes a scale from the state.
	 *
	 * # Arguments
	 *
	 * * `scale_id` - The id of the scale to remove.
	 *
	 * # Returns
	 * * `None` - If the scale was not found.
	 * * `Some(scale)` - If the scale was found and removed.
	 */
	removeScale(scaleId: string): Scale | null;
	/**
	 * Get the measurements that are missing a scale.
	 *
	 * # Returns
	 *
	 * * `Vec<MeasurementWrapper>` - The measurements that are missing a scale.
	 */
	getMeasurementsMissingScale(): Array<MeasurementWrapper>;
}

/** Add 100 to the input */
export declare function plus100(input: number): number;

/** Add 200 to the input */
export declare function plus200(input: number): number;
export declare class UnitValue {
	constructor(value: number, unit: Unit, magnitude: UnitValueItemType);
	display(unit: Unit): string;
	getConvertedValue(to: Unit): number;
}

export interface ContourInput {
	id: string;
	name?: string;
	pageId: string;
	/** The lines that make up the contour map */
	lines: Array<ContourLineInput>;
	/** The points of interest that are used to create the contour map */
	pointsOfInterest: Array<ContourPointOfInterestInput>;
}

export interface ContourLineInput {
	/** The elevation of the contour line (in pixels) */
	elevation: number;
	points: Array<Point>;
}

export interface ContourPointOfInterestInput {
	/** The elevation of the point of interest (in pixels) */
	elevation: number;
	point: Point;
}

/** Calculate distance between two points */
export declare function distance(
	points: [Point, Point] | [Point3D, Point3D],
): number;

export interface Group {
	id: string;
	name?: string;
	measurementType: MeasurementType;
}

export type Measurement =
	| {
			type: "Count";
			id: string;
			pageId: string;
			groupId: string;
			points: [Point];
	  }
	| {
			type: "Polygon";
			id: string;
			pageId: string;
			groupId: string;
			points: Array<Point>;
	  }
	| {
			type: "Polyline";
			id: string;
			pageId: string;
			groupId: string;
			points: Array<Point>;
	  }
	| {
			type: "Rectangle";
			id: string;
			pageId: string;
			groupId: string;
			points: [Point, Point];
	  };

export type MeasurementType = "Area" | "Linear" | "Count";

export interface Page {
	id: string;
	name?: string;
	width?: number;
	height?: number;
	viewport?: PageViewport;
}

export interface PageViewport {
	width: number;
	height: number;
}

/** Represents a 2D point with floating point coordinates */
export interface Point {
	x: number;
	y: number;
}

export interface Point3D {
	x: number;
	y: number;
	z: number;
}

/** Input for creating a reference surface from JS/TS. */
export type ReferenceSurfaceInput =
	| { type: "Polygon"; points: Array<Point>; elevation: number }
	| { type: "Rectangle"; points: [Point, Point]; elevation: number };

export type Scale =
	| {
			type: "Area";
			id: string;
			pageId: string;
			scale: ScaleDefinition;
			boundingBox: [Point, Point];
	  }
	| { type: "Default"; id: string; pageId: string; scale: ScaleDefinition };

export interface ScaleDefinition {
	pixelDistance: number;
	realDistance: number;
	unit: Unit;
}

/** Simplify a polyline using the Ramer-Douglas-Peucker algorithm */
export declare function simplifyPolyline(
	points: Array<Point>,
	tolerance: number,
): Array<Point>;

export interface StateOptions {
	pages: Array<Page>;
	groups: Array<Group>;
	measurements: Array<Measurement>;
	scales: Array<Scale>;
}

/** Measurement units supported by the system */
export type Unit =
	/** Imperial units */
	| "Yards"
	| "Feet"
	| "Inches"
	/** Metric units */
	| "Meters"
	| "Centimeters";

export type UnitValueItemType = "Area" | "Length";

/** Result of a volumetric cut/fill calculation. */
export interface VolumetricResult {
	/** Volume to remove (terrain above reference). */
	cut: number;
	/** Volume to add (terrain below reference). */
	fill: number;
	/** Area where terrain data was unavailable (z_at returned None). */
	uncoveredArea: number;
}
